/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment2;

import java.lang.annotation.*;

public class App {
    @Generated
    public static void main(String[] args) {
        UI ui = new UI();
        ui.begin();
    }

    // This is to skip the unit test in jacocoTestReport because we do not need to
    // test this file
    @Documented
    public @interface Generated {
    }
}
