/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment_1;

public class App {
    public static void main(String[] args) {
        // should work for gradle run
        ABCSystem sys = new ABCSystem();
        sys.run();
    }
}
