/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment_1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // Test the constructor
    @Test
    public void testAppConstructor() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
}
